#!/usr/bin/env sh

# Autohide the dock
defaults write com.apple.dock autohide -bool true

# Orient the dock to the right
defaults write com.apple.dock orientation right

# Clear dock of persistent apps
defaults write com.apple.dock persistent-apps '()'
defaults write com.apple.dock persistent-others '()'

# Disable "natural" scroll direction
defaults write -g com.apple.swipescrolldirection -bool false

# Disable haptic feedback
defaults write com.apple.AppleMultitouchTrackpad ActuateDetents -bool false
defaults write com.apple.AppleMultitouchTrackpad ForceSuppressed -bool true

# Enable tap to click
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true

# Disable automatic spelling and grammar corrections
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticTextCompletionEnabled -bool false
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false

# Set screen capture save location
mkdir -p $HOME/tmp/screencapture
defaults write com.apple.screencapture location -string "$HOME/tmp/screencapture"

# Disable screen capture shadow
defaults write com.apple.screencapture disable-shadow -bool true

# Set screen capture default format
defaults write com.apple.screencapture type -string "png"

# Show expanded finder in save dialog
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Show hidden files in finder
defaults write com.apple.finder AppleShowAllFiles -bool true

# Show status bar in finder
defaults write com.apple.finder ShowStatusBar -bool true

# Show path in finder
defaults write com.apple.finder ShowPathbar -bool true

# Sort with folder at top in finder
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Default search scope is current folder in finder
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

# Default view to list in finder
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# Enable option+scroll to zoom screen
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess closeViewScrollWheelModifiersInt -int 524288

# Double click to maximize
defaults write NSGlobalDomain AppleActionOnDoubleClick -string "Maximize"

# Hot Corners:
#  2  = mission control
#  3  = application windows
#  4  = desktop
#  10 = sleep
defaults write com.apple.dock wvous-tr-corner -int 2
defaults write com.apple.dock wvous-bl-corner -int 4
defaults write com.apple.dock wvous-br-corner -int 3

# Disable boot chime
sudo nvram StartupMute=%01

# Restart
killall Dock
killall Finder
killall SystemUIServer
