#!/bin/bash -ea

################################################################################
# 
# Written by https://github.com/jzbruno
#
# bash script to login to a vpn that uses symantec vip access in automated way
#
# Requires:
#     vip script to get otp from https://github.com/ykhemani/vipaccess
#     vpn password stored in keychain
#
################################################################################

vpn_uri=$1
username=$2
otp=`./vip`
password=`security find-generic-password -ga ${username} 2>&1 >/dev/null | cut -d '"' -f2`

printf '%s%s' "${password}" "${otp}" | sudo openconnect -q --user=${username} $vpn_uri
